# Plotting the data to inspect relationships
plot(fulldata[, c(dv, "TOT_LVG_AREA", "RAIL_DIST", "CNTR_DIST", "age", "structure_quality")], col=rgb(0.7, 0.7, 0.7, 0.3)) # inspecting the relationships between the data

# Visualizing the tree
rpart.plot(tree, type = 2)

# DESCRIPTION: The top value is the average house price for the houses included within a certain node. The lower value represents the percentage of the whole data which is included at that node (and therefore satisfies the decision criteria at every split up to that point).

# COMMENT: In classification trees there is one more value in each node, just between the two just described values, which is the probability. See https://www.guru99.com/r-decision-trees.html for an extensive explanation of classification trees.

printcp(tree)

# DESCRIPTION: The parameters included in the output of printcp() are the following:
# - CP: Complexity Parameter. A smaller cp gives a more complex model_formula, i.e., more splits.
# - nsplit: Literally it is the number of splits. A tree with nsplit = 0 is just a single leaf.
#           A tree with nsplit equal to 1 will have 2 leaves. A tree with nsplit = 2 will have 3
#           leaves and so on. A leaf is a node that has no child nodes (terminal node).
# - rel error: This is the error on the observations used to estimate the model_formula. Multiply by baseline error to get the corresponding absolute error measure.
# - xerror: Cross validation error estimate. It is generated by the rpart built-in cross validation.
# - xstd: Standard error.
# See https://maths-people.anu.edu.au/~johnm/courses/dm/math3346/2006/pdf/r-exs9.pdf for reference.

# DESCRIPTION: How are these parameters calculated?
# - CP: CP_n is obtained by (rel error_n - rel error_(n+1))/(nsplit_(n+1)-nsplit_n) (https://stats.stackexchange.com/questions/117908/rpart-complexity-parameter-confusion).
#   e.g., for nsplit 10:
#     (tree_cp[10, "rel error"] - tree_cp[11, "rel error"]) / (tree_cp[11, "nsplit"] - tree_cp[10, "nsplit"])
# - rel error: 1 - R^2, similar to linear regression (https://stats.stackexchange.com/questions/103018/difference-between-rel-error-and-xerror-in-rpart-regression-trees).
# - xerror: It is computed using a 10-fold cross-validation.
# - xstd:

# As we can see, printcp() automatically prints out the optimal number of nodes basing onthe CP (Complexity Parameter). rpart does not always deliver a pruned tree (see: https://stackoverflow.com/questions/13136683/is-rpart-automatic-pruning#:~:text=No%2C%20but%20the%20defaults%20for,definition%20of%20%22early%22).) Sometimes, we need to prune it on our own by considering the xerror and cp. The convention says that we should select the CP from the list with the smallest cross-validated error (xerror in the table). In other words, we shall select the lowest xerror, then prune the tree by setting the CP equal to the CP corresponding to such error.

# Visualizing the pruned tree
rpart.plot(prune_tree)

printcp(tree_fun)

# And we see that now the tree presents a higher number of splits. In fact, as the cp decreases, the number of splits increases and the tree gets deeper (see: https://stats.stackexchange.com/questions/251618/complexity-parameter-zero-in-decision-trees)

# Setting the cp = 0.01 is a convention, which usually provides the most efficient tree. Hence, oversplitting the tree and then using prune() usually brings the same result of running the tree with a cp = 0.01 (https://stackoverflow.com/questions/47029277/result-of-rpart-is-a-root-but-data-shows-information-gain).

## Showing the set of possible cost-complexity prunings of a tree from a nested set with plotcp().
# https://rdrr.io/cran/itree/man/plotcp.html
# We can compare the tree before vs after pruning
plotcp(tree)
plotcp(prune_tree)

# DESCRIPTION: What is the dotted line in plotcp()? The function plots the cp values against their related xerror, with st dev included.The dotted line represents the highest cross-validated error less than the minimum cross-validated error plus 1 standard deviation of the error at that tree. See https://stackoverflow.com/questions/21698540/whats-the-meaning-of-plotcp-result-in-rpart for reference.

# Visualizing a tree with cp = 0.007
rpart.plot(tree_fun, type = 2)

